openapi: 3.0.1
info:
  title: Foundations_DataEncryption_ClearDataRetrieval_Digital_Domain_OpenAPI
  description: This API is used to retrieve the clear account number.
  version: 1.0.1
  x-deployment-reference: RetrieveUnmaskedAccountData
  x-linked-api: RetrieveUnmaskedAccountData
servers:
- url: https://127.0.0.1/openapi/v1/accounts/clearData/retrieve
paths:
  /:
    post:
      tags:
      - Foundations_Utilities_Data Encryption
      summary: Retrieve Clear Account Number
      description: This API is used to retrieve the clear account number.
      operationId: RetrieveUnmaskedAccountData
      parameters:
      - $ref: "#/components/parameters/Authorization"
      - $ref: "#/components/parameters/uuid"
      - $ref: "#/components/parameters/Accept"
      - $ref: "#/components/parameters/client_id"
      - $ref: "#/components/parameters/Content-Type"
      - $ref: "#/components/parameters/clientDetails"
      requestBody:
        description: RetrieveUnmaskedAccountDataRequest
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RetrieveUnmaskedAccountDataRequest"
        required: true
      responses:
        "200":
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RetrieveUnmaskedAccountDataResponse"
        "400":
          description: <table><tr><td>Type</td><td>Code</td><td>Details</td></tr><tr><td>invalid</td><td>invalidRequest</td><td>Missing
            or invalid parameters</td></tr></table>
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: <table><tr><td>Type</td><td>Code</td><td>Details</td></tr><tr><td>error</td><td>unAuthorized</td><td>Authorization
            credential is missing or invalid</td></tr></table>
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "403":
          description: <table><tr><td>Type</td><td>Code</td><td>Details</td></tr><tr><td>error</td><td>accessNotConfigured</td><td>The
            request operation is not configured to access this resource</td></tr></table>
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: <table><tr><td>Type</td><td>Code</td><td>Details</td></tr><tr><td>error</td><td>resourceNotFound</td><td>Empty
            resource/resource not found</td></tr></table>
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: <table><tr><td>Type</td><td>Code</td><td>Details</td></tr><tr><td>error</td><td>businessValidationsFailed</td><td>Business
            validations failed</td></tr></table>
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: <table><tr><td>Type</td><td>Code</td><td>Details</td></tr><tr><td>fatal</td><td>serverUnavailable</td><td>The
            request failed due to an internal error</td></tr></table>
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
      x-codegen-request-body-name: RetrieveUnmaskedAccountDataRequest
components:
  schemas:
    RetrieveUnmaskedAccountDataRequest:
      type: object
      properties:
        accountInfo:
          type: array
          items:
            $ref: "#/components/schemas/AccountInfo"
    AccountInfo:
      required:
      - accountId
      type: object
      properties:
        accountId:
          type: string
          description: "The account identifier in encrypted format.Typically, this\
            \ is not displayed to the customer."
          example: 36497956776473644d3775334144505a7a7867375a564c656c31707a586655536f366c30643545644d78453d
    RetrieveUnmaskedAccountDataResponse:
      type: object
      properties:
        accounts:
          type: array
          items:
            $ref: "#/components/schemas/Accounts"
    Accounts:
      required:
      - accountId
      - unmaskedAccountNumber
      type: object
      properties:
        unmaskedAccountNumber:
          type: string
          description: An unmasked IBAN (International bank account number)to be displayed
            to the customer
          example: 8.01030001901098E25
        accountId:
          type: string
          description: "The account identifier in encrypted format.Typically, this\
            \ is not displayed to the customer."
          example: 36497956776473644d3775334144505a7a7867375a564c656c31707a586655536f366c30643545644d78453d
    ErrorResponse:
      required:
      - code
      - type
      type: object
      properties:
        type:
          type: string
          description: Invalid - Request did not confirm to the specification and
            was unprocessed and rejected. Please fix the value and try again
          enum:
          - error
          - warn
          - invalid
          - fatal
        code:
          type: string
          description: Error code which qualifies the error
        details:
          type: string
          description: Human readable explanation specific to the occurrence of the
            problem
        location:
          type: string
          description: The name of the field that resulted in the error
        moreInfo:
          type: object
          properties: {}
          description: URI to human readable documentation of the error
  parameters:
    Authorization:
      name: Authorization
      in: header
      description: "The most recent Authorization token. This will have the format\
        \ Bearer + {space} + {accessToken}. Example: Bearer KGNsaWVudF9pZDpjbGllbnRfc2VjcmV0KQ==."
      required: true
      style: simple
      explode: false
      schema:
        type: string
    uuid:
      name: uuid
      in: header
      description: 128 bit random universally unique identifier (UUID) generated for
        every request.
      required: true
      style: simple
      explode: false
      schema:
        type: string
    Accept:
      name: Accept
      in: header
      description: Content-Types that are acceptable for the response. Always pass
        application/json.
      required: true
      style: simple
      explode: false
      schema:
        type: string
    client_id:
      name: client_id
      in: header
      description: Client ID generated during application registration.
      required: true
      style: simple
      explode: false
      schema:
        type: string
    Content-Type:
      name: Content-Type
      in: header
      description: application/json.
      required: true
      style: simple
      explode: false
      schema:
        type: string
    clientDetails:
      name: clientDetails
      in: header
      description: "This field is used to capture device,browser and network information.\
        \ Refer the developer portal for more information.These are the fields which\
        \ will be passed as part of the header devicePrint,deviceTokenCookie,userIpAddress,userAgent,hardwareId,simId,deviceModel,deviceName,deviceOsName,deviceOsVersion,multitaskingSupportFlag,languageSupport,wifiMacAddress,cellTowerId,locationAreaCode,rsaApplicationKey,wapClientId,mobileCarrierCode,mobileCountryCode,osId,geoLongitude,geoLatitude,geoHorizontalAccuracy,geoAltitude,geoAltitudeAccuracy,geoSpeed,geoTimestamp,geoStatus,basicServiceSetId,signalStrength,wifiChannel,serviceSetId."
      required: false
      style: simple
      explode: false
      schema:
        type: string
