openapi: 3.0.1
info:
  title: Oauth2ClientCredentialTokenManagement_OpenAPI
  description: The access token resource using client credentials grant type
  version: 1.2.99
  x-deployment-reference: ""
  x-linked-api: Access-token-client-credentials-base
servers:
- url: https://127.0.0.1/openapi/clientCredentials/oauth2/token
security:
- client_secret: []
  client_id: []
paths:
  /{countryCode}/{businessCode}:
    post:
      tags:
      - Client Credentials Grant - Token Endpoint
      summary: "Client Credentials grant: Retrieve access token"
      description: Token endpoint for retrieving access token for the grant type "client_credentials"
      parameters:
      - name: Authorization
        in: header
        description: "HTTP Basic authentication by passing base64 encoded value of\
          \ the client id and client secret separated by colon (:).Example: Base64(client_id:client_secret)\
          \ will be passed as Basic KGNsaWVudF9pZDpjbGllbnRfc2VjcmV0KQ=="
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: Content-Type
        in: header
        description: Value should always be application/x-www-form-urlencoded
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: countryCode
        in: path
        description: countryCode
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: businessCode
        in: path
        description: businessCode
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - grant_type
              - scope
              properties:
                grant_type:
                  type: string
                  description: The grant type. Valid value is client_credentials.
                scope:
                  type: string
                  description: The set of scopes requested to make API calls. You
                    can pass multiple values delimted by space
        required: true
      responses:
        "200":
          description: The request has succeeded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokenResponse"
        "400":
          description: <table><tr><td>error</td></tr> <tr><td>invalid_request</td></tr>
            <tr><td>invalid_grant</td></tr> <tr><td>unsupported_grant_type</td></tr>
            <tr><td>unauthorized_client</td></tr> </table>
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: <table><tr><td>error</td></tr> <tr><td>invalid_client</td></tr>
            </table>
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: server_error
          content: {}
components:
  schemas:
    AccessTokenResponse:
      required:
      - access_token
      - consented_on
      - expires_in
      - scope
      - token_type
      type: object
      properties:
        token_type:
          type: string
          description: Type of the access token issued.
          example: bearer
        access_token:
          type: string
          description: This field should be passed as Authorization header in API
            request calls
          example: AAEkYzFjMDQ0Y2UtNTBmMy00NmY4LWI4YjEtYmQ5ODJkMWZiNGZh3xGP85xjqyxoHR7pXxzQJf223kWPL-HyWHD4zrRCvHZUkeBkTgxppbmpFtmWeVmjzDOxs1wFzI4s45YDS15eYmyuxzLbVog4d8H9pYSelrvL6naDYOLL9U16EaY0iyAMPBGX1H7RhCqtmd-7u_Eanw7QshbruLaZh2stOrdq2thC5CCSwW2r0e8PM1QbWubJOcMp8UGv-zNc0I3cTSihymSCF44HJ_yeuPAcXJ7kj-iPzQqxaO6FiWPmIsIh2YSxdGYo8alTyjJfG5AQDnM0HA
        expires_in:
          type: number
          description: Validity of access token in seconds
          example: 3600
        consented_on:
          type: number
          description: This refer to the customer consent time for authorization
          example: 1606116479
        scope:
          type: string
          description: The set of scopes requested to make API calls
          example: /dda/accountlist /dda/account
    ErrorResponse:
      required:
      - error
      type: object
      properties:
        error:
          type: string
          description: "If the request fails due to a missing, invalid, or mismatching\
            \ redirection URI, or if the client identifier is missing or invalid,\
            \ the authorization server SHOULD inform the resource owner of the error\
            \ and MUST NOT automatically redirect the user-agent to the invalid redirection\
            \ URI."
          enum:
          - invalid_request
          - unauthorized_client
          - access_denied
          - unsupported_response_type
          - invalid_scope
          - server_error
          - temporarily_unavailable
        error_description:
          type: string
          description: "Human-readable ASCII [USASCII] text providing additional information,\
            \ used to assist the client developer in understanding the error that\
            \ occurred"
        error_uri:
          type: string
          description: "A URI identifying a human-readable web page with information\
            \ about the error, used to provide the client developer with additional\
            \ information about the error."
  securitySchemes:
    client_secret:
      type: apiKey
      description: ""
      name: X-IBM-Client-Secret
      in: header
    client_id:
      type: apiKey
      description: pv52735
      name: X-IBM-Client-Id
      in: header
